import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

import '/services/cms_content_service.dart';

/// Topics for which we show a one-time, in-app disclosure before the first
/// time we trigger a sensitive permission prompt or AI interaction.
///
/// Apple and Google both ask for an in-context purpose string before the
/// system permission dialog; this service centralizes that copy so every
/// surface tells the user the same thing.
enum FoCoCoDisclosureTopic {
  microphone,
  location,
  ai,
}

class FoCoCoDisclosureCopy {
  const FoCoCoDisclosureCopy({
    required this.title,
    required this.body,
    required this.policyUrl,
    required this.continueLabel,
  });

  final String title;
  final String body;
  final String policyUrl;
  final String continueLabel;
}

const Map<FoCoCoDisclosureTopic, FoCoCoDisclosureCopy> _kDisclosures = {
  FoCoCoDisclosureTopic.microphone: FoCoCoDisclosureCopy(
    title: 'FoCoCo uses your microphone',
    body:
        'FoCoCo records voice during coaching sessions and Golf Chat to give '
        'you real-time mental performance feedback. Audio leaves your device '
        'only for AI processing and is handled per our privacy policy.',
    policyUrl: 'https://www.fococo.ai/privacy-policy',
    continueLabel: 'Continue',
  ),
  FoCoCoDisclosureTopic.location: FoCoCoDisclosureCopy(
    title: 'FoCoCo uses your location',
    body:
        'Location data powers golf-course context, hole tracking, and '
        'session insights. We only use it while you are using FoCoCo.',
    policyUrl: 'https://www.fococo.ai/privacy-policy',
    continueLabel: 'Continue',
  ),
  FoCoCoDisclosureTopic.ai: FoCoCoDisclosureCopy(
    title: 'You are talking to an AI coach',
    body:
        'FoCoCo coaching responses are generated by an AI system, not a '
        'human coach. They are educational and not a substitute for medical '
        'or psychological advice.',
    policyUrl: 'https://www.fococo.ai/ai-disclosure',
    continueLabel: 'Got it',
  ),
};

class FirstUseDisclosureService {
  FirstUseDisclosureService._();

  static final FirstUseDisclosureService instance =
      FirstUseDisclosureService._();

  static const String _prefsPrefix = 'fococo.first_use.disclosure.';

  /// Show the disclosure once. If the user has already acknowledged the
  /// topic, this returns true immediately. Returns false if the user
  /// dismisses the dialog without acknowledging.
  Future<bool> ensureAcknowledged(
    BuildContext context,
    FoCoCoDisclosureTopic topic,
  ) async {
    final cmsFields = CmsContentService.instance.disclosureFields(topic.name);
    final copy = cmsFields != null
        ? FoCoCoDisclosureCopy(
            title: cmsFields['title']!,
            body: cmsFields['body']!,
            policyUrl: cmsFields['policyUrl']!,
            continueLabel: cmsFields['continueLabel'] ?? 'Continue',
          )
        : _kDisclosures[topic];
    if (copy == null) return true;

    final prefs = await SharedPreferences.getInstance();
    final key = '$_prefsPrefix${topic.name}';
    if (prefs.getBool(key) == true) {
      return true;
    }

    if (!context.mounted) return false;

    final accepted = await showDialog<bool>(
      context: context,
      barrierDismissible: false,
      builder: (dialogCtx) => AlertDialog(
        title: Text(copy.title),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(copy.body, style: const TextStyle(height: 1.45)),
              const SizedBox(height: 12),
              InkWell(
                onTap: () async {
                  final uri = Uri.parse(copy.policyUrl);
                  if (await canLaunchUrl(uri)) {
                    await launchUrl(uri,
                        mode: LaunchMode.externalApplication);
                  }
                },
                child: Text(
                  copy.policyUrl,
                  style: const TextStyle(
                    decoration: TextDecoration.underline,
                  ),
                ),
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogCtx).pop(false),
            child: const Text('Cancel'),
          ),
          FilledButton(
            onPressed: () => Navigator.of(dialogCtx).pop(true),
            child: Text(copy.continueLabel),
          ),
        ],
      ),
    );

    if (accepted == true) {
      await prefs.setBool(key, true);
      return true;
    }
    return false;
  }
}
